import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/ui/layout/header";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col font-inter bg-[#F6F1EB] lg:px-20 md:px-6 px-4 pt-10`}>
        <Header />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
